<dec f='include/c++/12/bits/functexcept.h' l='66' type='void std::__throw_logic_error(const char * )'/>
<use f='include/c++/12/bits/basic_string.h' l='618' u='c' c='_ZNSt7__cxx1112basic_stringC1EPKT_N9__gnu_cxx14__alloc_traitsINS5_IT1_NS6_10value_typeEE6rebindIS1_E5otherENSA_5other10value_typeEE9size_typeERKS6_'/>
<use f='include/c++/12/bits/basic_string.h' l='639' u='c' c='_ZNSt7__cxx1112basic_stringC1EPKT_RKT1_'/>
<use f='include/c++/12/bits/locale_conv.h' l='238' u='c' c='_ZNSt8__detail11_Scoped_ptrC1EPT_PKc'/>
<doc f='include/c++/12/bits/functexcept.h' l='64'>// Helpers for exception objects in &lt;stdexcept&gt;</doc>
<use f='include/c++/12/bitset' l='953' u='c' c='_ZNSt6bitsetC1EPKTL0__NSt7__cxx1112basic_stringIS0_St11char_traitsIS0_ESaIS0_EE9size_typeES0_S0_'/>
