<dec f='include/c++/10/bits/exception_ptr.h' l='70' type='void std::rethrow_exception(std::__exception_ptr::exception_ptr )'/>
<dec f='include/c++/10/bits/exception_ptr.h' l='92' type='void std::rethrow_exception(std::__exception_ptr::exception_ptr )'/>
<use f='include/c++/10/bits/nested_exception.h' l='70' u='c' c='_ZNKSt16nested_exception14rethrow_nestedEv'/>
<use f='tvm/3rdparty/dmlc-core/include/dmlc/common.h' l='85' u='c' c='_ZN4dmlc12OMPException7RethrowEv'/>
<doc f='include/c++/10/bits/exception_ptr.h' l='69'>/// Throw the object pointed to by the exception_ptr.</doc>
<use f='include/c++/10/future' l='730' u='c' c='_ZNKSt14__basic_future13_M_get_resultEv'/>
