<dec f='include/c++/10/bits/exception_ptr.h' l='64' type='std::__exception_ptr::exception_ptr std::current_exception()'/>
<dec f='include/c++/10/bits/exception_ptr.h' l='91' type='std::__exception_ptr::exception_ptr std::current_exception()'/>
<use f='include/c++/10/bits/exception_ptr.h' l='201' u='c' c='_ZSt18make_exception_ptrT_'/>
<use f='include/c++/10/bits/nested_exception.h' l='57' u='c' c='_ZNSt16nested_exceptionC1Ev'/>
<doc f='include/c++/10/bits/exception_ptr.h' l='60'>/** Obtain an exception_ptr to the currently handled exception. If there
   *  is none, or the currently handled exception is foreign, return the null
   *  value.
   */</doc>
<use f='include/c++/10/future' l='1358' u='c' c='_ZNKSt13__future_base12_Task_setterclEv'/>
<use f='include/c++/10/future' l='1381' u='c' c='_ZNKSt13__future_base12_Task_setterIT_T0_vEclEv'/>
